security:
    password_hashers:
        hasher:
            id: App\User\Infrastructure\Auth\PasswordHasher

    providers:
        users:
            id: 'App\User\Infrastructure\Auth\AuthProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_healthz:
            pattern:  ^/api/healthz
            stateless: true

        api_doc:
            pattern:  ^/api/doc
            stateless: true

        api_auth:
            pattern:  ^/api/auth
            stateless: true

        api_signup:
            pattern:  ^/api/signup
            stateless: true

        api_secured:
            pattern:  ^/api
            provider: users
            stateless: true
            jwt: ~

        secured_area:
            pattern: ^/
            provider: users
            custom_authenticators:
            - 'App\User\Infrastructure\Auth\Guard\LoginAuthenticator'
            form_login:
              login_path: /sign-in
              check_path: sign-in
            entry_point: form_login
            logout:
              path: /logout
              target: /

    access_control:
        - { path: ^/profile,      roles: ROLE_USER }
        - { path: ^/api/healthz, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth,    roles: PUBLIC_ACCESS }
        - { path: ^/api/signup,  roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,     roles: PUBLIC_ACCESS }
        - { path: ^/api/,        roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/,            roles: PUBLIC_ACCESS }
